"""Generate SMC_ICT_Pro_Strategy.pine from the indicator.

The strategy is the indicator with TradingView orders wired into the same
trade tracker (hooks marked ``//@@ARM``, ``//@@CANCEL``, ``//@@BE``) so the
two can never drift apart. Run after editing the indicator:

    python tradingview/build_strategy.py
"""

from __future__ import annotations

import re
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / "SMC_ICT_Pro.pine"
DST = HERE / "SMC_ICT_Pro_Strategy.pine"

DECL = (
    'strategy("SMC ICT Pro - Strategy", shorttitle = "SMC ICT Pro S", overlay = true, '
    "max_boxes_count = 500, max_lines_count = 500, max_labels_count = 500, max_bars_back = 1000, "
    "initial_capital = 10000, commission_type = strategy.commission.percent, commission_value = 0.02, "
    "slippage = 0, pyramiding = 0, process_orders_on_close = false)"
)

RISK_INPUT = (
    'riskPct      = input.float(0.5, "Risk per trade (% of equity)", minval = 0.01, step = 0.05, '
    'group = G_SET, tooltip = "Position size = equity x risk% / stop distance.")'
)

HOOKS = {
    "//@@ARM": [
        'strategy.cancel("SMC")',
        "float qtyUnits = strategy.equity * riskPct / 100 / math.abs(e - sl)",
        'strategy.entry("SMC", pick == 1 ? strategy.long : strategy.short, qty = qtyUnits, limit = e)',
        'strategy.exit("SMC exit", from_entry = "SMC", stop = sl, limit = tp)',
    ],
    "//@@CANCEL": ['strategy.cancel("SMC")'],
    "//@@BE": ['strategy.exit("SMC exit", from_entry = "SMC", stop = cur.slCur, limit = cur.tp)'],
}


def build() -> str:
    src = SRC.read_text()
    out: list[str] = []
    skipping = False
    for line in src.split("\n"):
        stripped = line.strip()
        if stripped.startswith("indicator("):
            out.append(DECL)
            continue
        if stripped == "//@@ALERTCONDITIONS_BEGIN":
            skipping = True
            continue
        if stripped == "//@@ALERTCONDITIONS_END":
            skipping = False
            continue
        if skipping:
            continue
        if stripped in HOOKS:
            indent = line[: len(line) - len(line.lstrip())]
            out.extend(indent + code for code in HOOKS[stripped])
            continue
        out.append(line)
        if re.match(r"^showDash\s", line):
            out.append(RISK_INPUT)
    text = "\n".join(out)
    text = text.replace(
        "// Smart Money Concepts / ICT toolkit + the entry models",
        "// STRATEGY build (generated by build_strategy.py - edit SMC_ICT_Pro.pine instead)\n"
        "// Smart Money Concepts / ICT toolkit + the entry models",
        1,
    )
    return text


if __name__ == "__main__":
    DST.write_text(build())
    print(f"wrote {DST}")
